# YAML configuration file for batch station extraction (processing.exstns.py)
# 20/04/2016, Andre R. Erler

NP: 2 # environment variable has precedence
# N.B.: station extraction tends to be relatively fast, but I/O limited
loverwrite: false # only recompute if source is newer
modes: ['time-series',]
varlist: Null # process all variables
periods: Null # climatology periods to process
# Datasets
datasets: Null # process all applicable
resolutions: Null # process all applicable
lLTM: false
# CESM
CESM_project: Null # all available experiments
load3D: false
CESM_experiments: Null
CESM_filetypes: ['atm','lnd']
# WRF
WRF_project: Null # all available experiments (fast enough)
WRF_experiments: Null # all available experiments
domains: Null # inner domain onto inner domain 
WRF_filetypes: ['aux','srfc','xtrm','hydro','lsm','rad','plev3d']
#WRF_filetypes: ['hydro'] # process all filetypes except 'rad' and 'plev3d'
# define station data
stations:
  EC: # all Environment Canada weather stations
    - 'precip' # precip stations from EC module
    - 'temp' # temperature stations from EC module
