# YAML configuration file for batch regridding (processing.regrid.py)
# 20/04/2016, Andre R. Erler

NP: 3 # environment variable has precedence
loverwrite: false # only recompute if source is newer
modes: ['climatology',]
varlist: Null # process all variables
periods: [5,10,15,30] # climatology periods to process
# Datasets
datasets: Null # process all applicable
resolutions: Null # process all applicable
lLTM: true 
# CESM
CESM_project: Null # all available experiments
load3D: false
CESM_experiments: Null
CESM_filetypes: ['atm','lnd']
# WRF
WRF_project: 'GreatLakes' # only GreatLakes experiments
#WRF_project: 'WesternCanada' # all available experiments
#WRF_project: Null # all available experiments
WRF_experiments: Null # all available experiments
#[ # process WRF experiments on different grids
#  'new-v361-ctrl', 'new-v361-ctrl-2050', 'new-v361-ctrl-2100',
#  'erai-v361-noah', 'new-v361-ctrl', 'new-v36-clm',
#  'new-v36-nmp', 'new-v36-noah', 'erai-v36-noah', 'new-v36-clm',
#  'new-ctrl', 'new-ctrl-2050', 'new-ctrl-2100', 'cfsr-new', # new standard runs (arb3) 
#  'new-grell', 'new-grell-old', 'new-noah', 'v35-noah', # new sensitivity tests (arb3)
#]
domains: Null # inner domain onto inner domain 
WRF_filetypes: ['srfc','xtrm','hydro','lsm','rad','aux'] # process all filetypes except 'rad' and 'plev3d'
# grid to project onto
grids: # mapping with list of resolutions  
#  arb2: ['d01',] # inner Western Canada
  glb1: ['d01','d02',] # inner Great Lakes
#grw1: [Null] # Grand River Watershed, 1km resolution
  grw2: [Null] # Grand River Watershed, 5km resolution
