# YAML configuration file for batch shape averaging (processing.shpavg.py)
# 20/04/2016, Andre R. Erler

NP: 3 # environment variable has precedence
loverwrite: false # only recompute if source is newer
modes: ['time-series',] # 'climatology'
varlist: Null # process all variables
periods: [15,30] # climatology periods to process
# Datasets
datasets: Null # process all applicable
resolutions: Null # process all applicable
lLTM: false
# CESM
CESM_project: Null # all available experiments
load3D: false
CESM_experiments: Null
CESM_filetypes: ['atm','lnd']
# WRF
WRF_project: 'GreatLakes' # only GreatLakes experiments
#WRF_project: Null # all available experiments
WRF_experiments: Null # all available experiments
#[ # process WRF experiments on different grids
  # Western Canada
#  'max-ctrl','max-ens-A','max-ens-B','max-ens-C', # main "best" IC ensemble
#  'erai-max','cfsr-max','max-seaice-2050','max-seaice-2100',
#  'max-ctrl-2050','max-ens-A-2050','max-ens-B-2050','max-ens-C-2050',
#  'max-ctrl-2100','max-ens-A-2100','max-ens-B-2100','max-ens-C-2100',
#  'new-ctrl', 'new-ctrl-2050', 'new-ctrl-2100', 'cfsr-new', # new config (arb3)     
#  'old-ctrl', 'old-ctrl-2050', 'old-ctrl-2100', # old/default config
#  'ctrl-1', 'ctrl-ens-A', 'ctrl-ens-B', 'ctrl-ens-C', # new "standard" IC ensemble
#  'ctrl-2050', 'ctrl-ens-A-2050', 'ctrl-ens-B-2050', 'ctrl-ens-C-2050',
#  'ctrl-2100', 'ctrl-ens-A-2100', 'ctrl-ens-B-2100', 'ctrl-ens-C-2100',
  # Great Lakes
#  't-ctrl', 't-ens-A', 't-ens-B', 't-ens-C', 'erai-t', # Marc's ctrl ensemble
#  't-ctrl-2050', 't-ens-A-2050', 't-ens-B-2050', 't-ens-C-2050',
#  't-ctrl-2100', 't-ens-A-2100', 't-ens-B-2100', 't-ens-C-2100', # last three are 
#  'g-ctrl', 'g-ens-A', 'g-ens-B', 'g-ens-C', 'erai-t', # Marc's max ensemble
#  'g-ctrl-2050', 'g-ens-A-2050', 'g-ens-B-2050', 'g-ens-C-2050',
#  'g-ctrl-2100', 'g-ens-A-2100', 'g-ens-B-2100', 'g-ens-C-2100', # last three are not finished yet
#]
domains: Null # all domains
WRF_filetypes: ['aux','srfc','xtrm','hydro','lsm','rad'] # process all filetypes except 'rad' and 'plev3d'
# define shape data
shape_name: 'shpavg'
shapes:
  provinces: Null # all Canadian provinces from EC module
  basins: Null # all river basins (in Canada) from WSC module
# N.B.: averaging over many shapes is computationally very expensive
